//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sgmlWDM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class dtd {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal dtd() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sgmlWDM.dtd", typeof(dtd).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE wm [
        ///&lt;!ENTITY nbsp    &quot;&amp;#160;&quot; &gt;
        ///&lt;!ENTITY iexcl   &quot;&amp;#161;&quot; &gt;
        ///&lt;!ENTITY cent    &quot;&amp;#162;&quot; &gt;
        ///&lt;!ENTITY pound   &quot;&amp;#163;&quot; &gt;
        ///&lt;!ENTITY curren  &quot;&amp;#164;&quot; &gt;
        ///&lt;!ENTITY yen     &quot;&amp;#165;&quot; &gt;
        ///&lt;!ENTITY brvbar  &quot;&amp;#166;&quot; &gt;
        ///&lt;!ENTITY sect    &quot;&amp;#167;&quot; &gt;
        ///&lt;!ENTITY uml     &quot;&amp;#168;&quot; &gt;
        ///&lt;!ENTITY copy    &quot;&amp;#169;&quot; &gt;
        ///&lt;!ENTITY ordf    &quot;&amp;#170;&quot; &gt;
        ///&lt;!ENTITY laquo   &quot;&amp;#171;&quot; &gt;
        ///&lt;!ENTITY not     &quot;&amp;#172;&quot; &gt;
        ///&lt;!ENTITY shy     &quot;&amp;#173;&quot; &gt;
        ///&lt;!ENTITY reg     &quot;&amp;#174;&quot; &gt;
        ///&lt;!ENTITY macr    &quot;&amp;#175;&quot; &gt;
        ///&lt;!ENTITY deg     &quot;&amp;#176;&quot; &gt;
        ///&lt;!E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string entity_def4 {
            get {
                return ResourceManager.GetString("entity_def4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE wm [
        ///  &lt;!ENTITY copy   &quot;&amp;#161;&quot; &gt;
        ///  &lt;!ENTITY cent    &quot;&amp;#162;&quot; &gt;
        ///  &lt;!ENTITY pound   &quot;&amp;#163;&quot; &gt;]&gt;
        ///.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
    }
}
